=== boctavian96/XMLTechnologies/XMLTechnologies/XMLValidator/databaseSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/NewXMLSchema"
	xmlns:tns="http://www.example.org/NewXMLSchema"
	attributeFormDefault="unqualified" elementFormDefault="qualified">

	<element name="database" type="tns:tableName"></element>

	<complexType name="tableName">
		<sequence>
			<element name="authors" type="tns:author_member"
				maxOccurs="1" minOccurs="1" />
			<element name="departments" type="tns:department_member"
				maxOccurs="1" minOccurs="1">
			</element>
			<element name="publications" type="tns:publication_member"
				maxOccurs="1" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="authorType">
		<sequence>
			<element type="positiveInteger" name="id" maxOccurs="1"
				minOccurs="1" />
			<element type="string" name="firstname" maxOccurs="1"
				minOccurs="1" />
			<element type="string" name="lastname" maxOccurs="1"
				minOccurs="1" />
			<element type="string" name="address" maxOccurs="1"
				minOccurs="1" />
			<element type="string" name="mobile" maxOccurs="unbounded"
				minOccurs="1" />
			<element type="tns:affiliationType" name="affiliations"
				maxOccurs="1" minOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="author_member">
		<sequence>
			<element type="tns:authorType" name="author" minOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="department_member">
		<sequence>
			<element type="tns:departmentType" name="department"
				minOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="publication_member">
		<sequence>
			<element type="tns:publicationType" name="publication"
				minOccurs="1" />
		</sequence>
	</complexType>

	<complexType name="affiliationType">
		<sequence>
			<element name="departmentId" type="positiveInteger"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>

	<complexType name="departmentType">
		<sequence>
			<element name="id" type="positiveInteger" maxOccurs="1"
				minOccurs="1"></element>
			<element name="name" type="string" maxOccurs="1"
				minOccurs="1"></element>
		</sequence>
	</complexType>


	<complexType name="publicationType" mixed="false">
		<sequence>
			<element name="id" type="positiveInteger" minOccurs="1"
				maxOccurs="1"></element>
			<element name="type" minOccurs="1" maxOccurs="1">
				<simpleType>
					<restriction base="string">
						<enumeration value="Journal"></enumeration>
						<enumeration value="Conferinta"></enumeration>
						<enumeration value="Articol"></enumeration>
						<enumeration value="Volum Colectiv"></enumeration>
					</restriction>
				</simpleType>
			</element>
			<element name="name" type="string" minOccurs="1"
				maxOccurs="1"></element>
			<element name="year" type="positiveInteger" minOccurs="1"
				maxOccurs="1"></element>
			<element name="authors" type="tns:authorIdType" minOccurs="1"
				maxOccurs="unbounded">
			</element>
			<element name="ISBN" type="string" minOccurs="1"
				maxOccurs="1"></element>
			<element name="URL" type="string" minOccurs="1" maxOccurs="1"></element>
			<element name="citations" type="string" minOccurs="1"
				maxOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="authorIdType">
		<sequence>
			<element name="authorId" type="positiveInteger"
				maxOccurs="unbounded" minOccurs="1">
			</element>
		</sequence>
	</complexType>
</schema>

=== boctavian96/XMLTechnologies/XMLTechnologies/XMLValidator/databaseGenerated.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:database
	xmlns:tns="http://www.example.org/NewXMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/NewXMLSchema databaseSchema.xsd ">
  <tns:authors>
    <tns:author>
      <tns:id>1</tns:id>
      <tns:firstname>tns:firstname</tns:firstname>
      <tns:lastname>tns:lastname</tns:lastname>
      <tns:address>tns:address</tns:address>
      <tns:mobile>tns:mobile</tns:mobile>
      <tns:affiliations>
        <tns:departmentId>1</tns:departmentId>
      </tns:affiliations>
    </tns:author>
  </tns:authors>
  <tns:departments>
    <tns:department>
      <tns:id>1</tns:id>
      <tns:name>tns:name</tns:name>
    </tns:department>
  </tns:departments>
  <tns:publications>
    <tns:publication>
      <tns:id>1</tns:id>
      <tns:type>Journal</tns:type>
      <tns:name>tns:name</tns:name>
      <tns:year>1</tns:year>
      <tns:authors>
        <tns:authorId>1</tns:authorId>
      </tns:authors>
      <tns:ISBN>tns:ISBN</tns:ISBN>
      <tns:URL>tns:URL</tns:URL>
      <tns:citations>tns:citations</tns:citations>
    </tns:publication>
  </tns:publications>
</tns:database>

=== boctavian96/XMLTechnologies/XMLTechnologies/XMLValidator/database.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:database xmlns:tns="http://www.example.org/NewXMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/NewXMLSchema databaseSchema.xsd ">
<!-- Authors table -->
	<tns:authors>
		<tns:author>
			<tns:id>1</tns:id>
			<tns:firstname>Ionel</tns:firstname>
			<tns:lastname>Tigla</tns:lastname>
			<tns:address>Strada Nuferilor nr.2 Bucuresti</tns:address>
			<tns:mobile>075210230</tns:mobile>
			<tns:affiliations>
				<tns:departmentId>1</tns:departmentId>
			</tns:affiliations>
		</tns:author>

		<tns:author>
			<tns:id>2</tns:id>
			<tns:firstname>Dorin</tns:firstname>
			<tns:lastname>Peste</tns:lastname>
			<tns:address>Strada Carbunilor nr.18 Iasi</tns:address>
			<tns:mobile>0723331110</tns:mobile>
			<tns:affiliations>
				<tns:departmentId>1</tns:departmentId>
				<tns:departmentId>2</tns:departmentId>
			</tns:affiliations>
		</tns:author>

		<tns:author>
			<tns:id>3</tns:id>
			<tns:firstname>Leonardo</tns:firstname>
			<tns:lastname>Davinci</tns:lastname>
			<tns:address>Strada Victoria nr.1 Timisoara</tns:address>
			<tns:mobile>035552315</tns:mobile>
			<tns:affiliations>
				<tns:departmentId>1</tns:departmentId>
				<tns:departmentId>2</tns:departmentId>
				<tns:departmentId>3</tns:departmentId>
				<tns:departmentId>4</tns:departmentId>
			</tns:affiliations>
		</tns:author>

		<tns:author>
			<tns:id>4</tns:id>
			<tns:firstname>Dorel</tns:firstname>
			<tns:lastname>Mesteru</tns:lastname>
			<tns:address>Strada Mihai Viteazul nr.9 Timisoara</tns:address>
			<tns:mobile>-</tns:mobile>
			<tns:affiliations>
				<tns:departmentId>3</tns:departmentId>
			</tns:affiliations>
		</tns:author>
	</tns:authors>

	<!-- departments table -->
	<tns:departments>
		<tns:department>
			<tns:id>1</tns:id>
			<tns:name>Facultatea de Matematica si Informatica</tns:name>
		</tns:department>

		<tns:department>
			<tns:id>2</tns:id>
			<tns:name>Facultatea de Economie si Administrare a afacerilor</tns:name>
		</tns:department>

		<tns:department>
			<tns:id>3</tns:id>
			<tns:name>Facultatea de Filosofie si Gandire Abstracta</tns:name>
		</tns:department>

		<tns:department>
			<tns:id>4</tns:id>
			<tns:name>Facultatea de Arte Frumoase</tns:name>
		</tns:department>
	</tns:departments>

	<!-- Publications table -->
	<tns:publications>
		<tns:publication>
			<tns:id>1</tns:id>
			<tns:type>Jurnal</tns:type>
			<tns:name>Metode de prelucrare XML</tns:name>
			<tns:year>2019</tns:year>
			<tns:authors>
				<tns:authorId>3</tns:authorId>
			</tns:authors>
			<tns:ISBN>12345678</tns:ISBN>
			<tns:URL>google.com</tns:URL>
			<tns:citations>6320550</tns:citations>
		</tns:publication>

		<tns:publication>
			<tns:id>2</tns:id>
			<tns:type>Conferinta</tns:type>
			<tns:name>Kernelul monolitic vs microkernel</tns:name>
			<tns:year>2018</tns:year>
			<tns:authors>
				<tns:authorId>1</tns:authorId>
			</tns:authors>
			<tns:ISBN>11111128</tns:ISBN>
			<tns:URL>https:/techdifferences.com/difference-between-microkernel-and-monolithic-kernel.html
			</tns:URL>
			<tns:citations>50000</tns:citations>
		</tns:publication>

		<tns:publication>
			<tns:id>3</tns:id>
			<tns:type>Volum Colectiv</tns:type>
			<tns:name>Arta de a lenevi</tns:name>
			<tns:year>2019</tns:year>
			<tns:authors>
				<tns:authorId>3</tns:authorId>
				<tns:authorId>4</tns:authorId>
			</tns:authors>
			<tns:ISBN>2222222</tns:ISBN>
			<tns:URL>https:/michelewoodward.com/2007/07/22/the-art-of-being-lazy/</tns:URL>
			<tns:citations>550</tns:citations>
		</tns:publication>

		<tns:publication>
			<tns:id>4</tns:id>
			<tns:type>Jurnal</tns:type>
			<tns:name>Cum sa desenezi o maimuta</tns:name>
			<tns:year>2009</tns:year>
			<tns:authors>
				<tns:authorId>3</tns:authorId>
			</tns:authors>
			<tns:ISBN>12333111</tns:ISBN>
			<tns:URL>howtodrawamonkey.com</tns:URL>
			<tns:citations>33032210</tns:citations>
		</tns:publication>

		<tns:publication>
			<tns:id>4</tns:id>
			<tns:type>Conferinta</tns:type>
			<tns:name>Efectul cafelei asupra incalzirii globale</tns:name>
			<tns:year>2019</tns:year>
			<tns:authors>
				<tns:authorId>4</tns:authorId>
			</tns:authors>
			<tns:ISBN>Q124333</tns:ISBN>
			<tns:URL>mahCofee.com</tns:URL>
			<tns:citations>2140513</tns:citations>
		</tns:publication>

		<tns:publication>
			<tns:id>5</tns:id>
			<tns:type>Jurnal</tns:type>
			<tns:name>Transform IT in moneyz</tns:name>
			<tns:year>2019</tns:year>
			<tns:authors>
				<tns:authorId>2</tns:authorId>
			</tns:authors>
			<tns:ISBN>F13r10</tns:ISBN>
			<tns:URL>iwantmoneyz.com</tns:URL>
			<tns:citations>10212532</tns:citations>
		</tns:publication>

		<tns:publication>
			<tns:id>6</tns:id>
			<tns:type>Jurnal</tns:type>
			<tns:name>Art of making money in FotoSop</tns:name>
			<tns:year>2016</tns:year>
			<tns:authors>
				<tns:authorId>2</tns:authorId>
				<tns:authorId>4</tns:authorId>
			</tns:authors>
			<tns:ISBN>D21400</tns:ISBN>
			<tns:URL>google.com</tns:URL>
			<tns:citations>6320</tns:citations>

		</tns:publication>
	</tns:publications>
</tns:database>
